### ISSUE TITLE
Error when installing with `pip`

### ISSUE THREAD

**Issue by subhacom** [subhacom/argos#7]
On windows 10 trying to install with `pip` results in a compilation error:
```
Error compiling Cython file:
      ------------------------------------------------------------
      ...
                              bint show_diff=False):
          blurred_cur[:, :] = cv2.GaussianBlur(gray_cur, (kernel_width,
                                                    kernel_width), 0)

          cdef cnp.ndarray[unsigned char, ndim=2] frame_delta = cv2.absdiff(blurred_cur, blurred_prev)
          cdef cnp.int_t ret
               ^
      ------------------------------------------------------------

      argos\ccapture.pyx:47:9: 'int_t' is not a type identifier

...
 [1/3] Cythonizing argos/ccapture.pyx
      Traceback (most recent call last):
        File "C:\Users\raysu\miniforge3\envs\argos\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\raysu\miniforge3\envs\argos\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\raysu\miniforge3\envs\argos\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\raysu\AppData\Local\Temp\pip-build-env-b1cj5k6b\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\raysu\AppData\Local\Temp\pip-build-env-b1cj5k6b\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\raysu\AppData\Local\Temp\pip-build-env-b1cj5k6b\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 97, in <module>
        File "C:\Users\raysu\AppData\Local\Temp\pip-build-env-b1cj5k6b\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\raysu\AppData\Local\Temp\pip-build-env-b1cj5k6b\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: argos/ccapture.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by subhacom** [comment]
It was due to incompatibility with numpy. Fixed in pull request #8
